hash-format = "sha256"

[[files]]
file = "mods/accessories.pw.toml"
hash = "b8dcd81b72048d30a1a7182dd6163c3cbd9658e22fa84e9dd2387164a649dd01"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "0451dc4f6515b79d34787804283141613029af0de58e2769def4d70e3777625c"
metafile = true

[[files]]
file = "mods/alloy-forgery.pw.toml"
hash = "573bc2adfc72fb395c27c371568f0af20d0e83949637b6cf1b8a555a63814956"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "006b24892ead1f3b1319727bcd41c32db322e3eb61956825387c3788bfd9e168"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "2b153d649184fcf793de475b3b3beaf238f7b558226ffc57896096a7ddcd99ad"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "ab1e22cc66189067e002a204c70c553cc7cc0e738bd602f405d7cc37561260be"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "9f92d063b29316733455bcf5ca2c0f77f31a479d9c0ceb8c3557da177691131c"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "dd8057c40ff94e9a21a121583884f71c9a6b1eaa6f913ef46c5d1f9b37fe487f"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
hash = "2e8023b4e1107227e4adadabdcb48d96b6659134f9174d476899e077c1621a12"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "a2de85ebe9629568398185b5b9554bcc0c54e322b214d78368485a6074a66279"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "127f0a7311e4ecd77c0b96660e0ff873d78d253fffb68db6101eeb414de38bb1"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "3b45878fbe0e15944f9d4c159741548debf4d775fd9e2f9992dcd1719c08b3da"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "b1581bbfae9d16690f4022536da6567f000130c4ea5e04d92177c1bc61fea709"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "cf0ea0786cf67b126b589a71f311268eb96bc98f1e4b58467aad45cb9aa24dfd"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "7d227ef90b1918ceb348ade235a5d17c7894acbf387575e96c08920a5bad1bbb"
metafile = true

[[files]]
file = "mods/create-man-of-many-planes.pw.toml"
hash = "05e9862287954ca4ff2f1a4b160f73ee43ea3573d90919de9a4202d54da93adb"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "2c65b7ed826a2d147f0eb4788152b9f1ae878e0df102af58a9ea23ebd1c48f04"
metafile = true

[[files]]
file = "mods/create-ore-excavation.pw.toml"
hash = "62ee505db03ae305933198e59250095ca5403b65abf02fbee6d5216e02d5c10e"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "b79bc9976d5958f4b88ca23575e0d0dc677a2b06931108f6f7bc3fd3e46bb22c"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "8276518c6ba5c30439e6361e115d6b26cd0a96904f7792d1501013aa05c3512f"
metafile = true

[[files]]
file = "mods/dragon-mounts-sow-edition.pw.toml"
hash = "6f25cb3218fcdecfb0025b1ac6df225b3e12bbd8617e0928b71d517967af247d"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "60ed60f9aabbf48ea8cf183a1748a54b539db72e0fdbaf81575a9fa50fb4c627"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "724f38446c3830230388cec99fed286ff1e8580f0a82c1466c7d59bde4450c71"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "e286c31c1b559e037730992bdc995383f6e783baa7b8c6c625e52c48a509d8b0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "431846491318f66fdef523f169044383847e75d3e1ff36cccd2bf8cb10e85ae8"
metafile = true

[[files]]
file = "mods/extra-mod-integrations.pw.toml"
hash = "376321a4e11e86d932670192b6ddebfd7b898c4e47e74a6b08c7c0123a0aa49c"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2d44be0de504bd05e2f6f2e4644f5d7afd2401adcdff92c19871db204e121988"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "97e7fb0bf5c563366b7c6121fa2decb67597107e5594932c6a098cccc980629e"
metafile = true

[[files]]
file = "mods/fastmove.pw.toml"
hash = "eb6f90591c0f013822b97d58f6e28fe50c8134e575a15a4588a491531a574d64"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "4449401b59481016fa2a66d6e749795129160cb1ab3e7932e15033c6b5815455"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
hash = "2fcd17a965738c1649d434a0d5f8077321b4bb90a8c9d9d868d220d8bbd5abb3"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "493ed95320ee3cc9c2def86b9d0971c2ca4bb4215921c2a11208bee77d5dbfb5"
metafile = true

[[files]]
file = "mods/happy-ghast.pw.toml"
hash = "8c5cd669a2359acb7d181d1ee2f1e904846dcb0959074bc6000f001697617e5d"
metafile = true

[[files]]
file = "mods/hephaestus-expansion.pw.toml"
hash = "23d1808185b96ba7e674ae80763db201b3fc1a4f05e54b0175105fe57bfaa8f7"
metafile = true

[[files]]
file = "mods/hephaestus.pw.toml"
hash = "da53b078e3d222c72a3dc7f065cca1cad9772473a6be401f4e7098c0e7da6456"
metafile = true

[[files]]
file = "mods/hephaestusplus.pw.toml"
hash = "6eb54613d2aafdb6d08fc3c820366c6441fa2ecc69c7e6215e52fc67e835c638"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "68985a3f3d2a6f829783c1bdbd27f195556992fc2c0a9738656acccf38d8c97a"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "1c4a41ca5c16702675d56211315bb8b87b943854a05fad31aaa606f0d7644ef9"
metafile = true

[[files]]
file = "mods/immersive-optimization.pw.toml"
hash = "18505a786dfcdfdbbb27dbba601e48e28298ace70a040dccbfecbfb84f8fdf12"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "465d7aac3ab99e38561354e331b640016f9ea82379b4d1e56b417bef8a881e92"
metafile = true

[[files]]
file = "mods/iris-flw-compat.pw.toml"
hash = "8619be4a2d5da2deff6cee6ebda356c1a7fdf3a36d8b58d31cd6ddd5b1649ca1"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/itemfig.pw.toml"
hash = "d33c83a7cfe86dd20c15d7607e0a57e809ed94d81bd0caf39a6d993f6238952d"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jupiter.pw.toml"
hash = "435014d4a5379337172a762d0f0b19aafd17a7ea06082facaf03c7089ad164c7"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "b4f42a6d80526e217e9f0f9fa698f6ef81697b94880803bcd5a14dd284bcb4b6"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "cc298019c2d3a47a97e72363b942fe408e5ecb7ff476fe08155793f2f1578317"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a08a445002542d96a8481654c3f4b5e2d3c064f77b477aeaa3a1d1c3cd396ca8"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "95c6186b4eb881f1bf6beea9aedefcc73388e4c301754e65722d85764243318b"
metafile = true

[[files]]
file = "mods/man-of-many-planes.pw.toml"
hash = "9c75a2572604803f8e03d00c98ef3b971fad40f9560676d564064a26e32b7a20"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "76c679c535e4d20c7eb671ed886dea84555aa5f220292b96e6955f3a00233a07"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "10d0880665a5abd65af746a8c473048a8ac0b3803631b3bcf18cee2eba0a1f28"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/mythicmetals-decorations.pw.toml"
hash = "0b9e799ac9640102061b5ae355504c82b34a2f606929cd89f9d71d8988db5d89"
metafile = true

[[files]]
file = "mods/mythicmetals.pw.toml"
hash = "9d72a2126537efbf86ea08ad99994739765b8402e18cad97835931b478b2c584"
metafile = true

[[files]]
file = "mods/origins-classes.pw.toml"
hash = "727beac4d8109d8136ce3aa101040a80caa4b353e3262eaa6d6256ca38d818b3"
metafile = true

[[files]]
file = "mods/origins-plus-plus.pw.toml"
hash = "f065531ba831351afe0da0adb6ecd6034c6d303728b24f6cec3805c90f795fa1"
metafile = true

[[files]]
file = "mods/origins-umbrellas.pw.toml"
hash = "7ffba2d20153f6ad79284e1f70e8f5cf1768e86ce071874687fa8088b83666e7"
metafile = true

[[files]]
file = "mods/origins.pw.toml"
hash = "e7b1fcffc4ab3623898b392685dde6c06256f9a7724bf48e072b16769b5992c7"
metafile = true

[[files]]
file = "mods/originstweaks.pw.toml"
hash = "7d1b601db4e7ee51e6059b4b203a24f9612b573044de5ee95e94d2d8ccc64254"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
hash = "43b4a9ca9aaac5a16ed067aee92cafaf30d6166d62d7fa851179c6257ed75b59"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "7ad4ca488da13998ce660729167eef71ce1bdfb57ef1c5d593096fa459cec0f8"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "e962db225d25099fbfb4729549dd053f3e3e222931fe8dc314e656e3efc39a89"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "a9769ced0531122518321833966d375196753db1c3a47b975aed4bb6837fae7a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "9ac19e450b2ab871a645079b185bdf976891c62702b4d3b07307941feee0632a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "bebd85acd6021b843e64c63a279dedf61875268a51ba69fb91ff86772aaf66bf"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "b4418b3889720386ad519a583735b7658679454f0ce8129d6f1c72a00f561b93"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b3ae602303fd717bff2344bfb89aa427e2b4a1ab5fffdcc25183b22102c492df"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/the-tube.pw.toml"
hash = "0e6f6e80ca7d08adef28fab955f7c2fc32e457bfef4535b93866789c8698e1c6"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "107f84db10d791aafb90e87d703bd267ede9b11a9c76490ccd1789f898411f01"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "407b6a954f9c3aee145dfa649eaa0b336a6b31d7660476c81cba1da1f6ff54e3"
metafile = true

[[files]]
file = "mods/weaponworks.pw.toml"
hash = "e769288d6426477d5ac341e78742cf3ae77f4c205df94cf573609e2b81591ffb"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "dba82d56d2514555ac3e326359a913c804b1a1137a6d696d80f73aadaf0ff62f"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "d5763cae561c3c23d431275e5d930a43bae2cc8e71f39a50a1b3d15b70a5b3f5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "95940b5fc72e8df82ab3adb72b43d10a37e6d926fbb37c405c9fe50bda27a991"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "0958d9f10d0e8fb282b8e684b05b37b29aca826d48deeec3e44171857c99aca5"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "c360a4aef0ce719d385529002ba157a731d572b73cefb573c763d71d54039078"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "a837a0028b1e1bbb6c4e5d31bf3cb04d6f6dccae90fc93df46f9a60a8b2c53c1"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "cf708ff146f867df2153b3f27482e80769c7032b10037e4a752d31fbb5668eaf"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "8bc20a4cf22bdd4406a64126647cfe3c704e80a3197031c9154032905a276705"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "f23d28e95b21a9655e615390a560bc66f3cb87610ac38cd9d849129d0600a766"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "b2af03e504a1827f2f6fc09597e7d51f4ecd64ab1ebb329a9eb9ffb98372673a"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "0b5eb310353cce6e94ffb0558cb713815b63328e6e96f804f147b5291c237a98"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "d201155cab7c2a2cf940d91f240be769ac12046c2fc6a0774e225a8e51423ed0"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "5df1b8ef822fe9987a65d412936909b4d700872db2ed107d0092e28452999101"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations-extensions.pw.toml"
hash = "e1958f3d85e8e248f316b08ea3211d0e90e860d3ed72d11776e5fd0662f84f24"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "b96abadb2cdb56d53145609e6a8ee9fd70171878bb5414412dddee1fca902a7b"
metafile = true

[[files]]
file = "resourcepacks/spbr.pw.toml"
hash = "1cc27f5b9dfe2a8cd3b8d43df0466b8086300e7cbd516785daf8910cee502f6e"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "fd18eb54847fd18feba9db1e9960c741cdaa6083c984773f8f79ae22182fad76"
metafile = true

[[files]]
file = "shaderpacks/photon-shader.pw.toml"
hash = "c8cf0916fb1562623afbe55df9d8451097fb15e11a09121cdadd714c982a4494"
metafile = true
